### ISSUE TITLE
Can't inject

### ISSUE THREAD

**Issue by chicken-nugget1104** [cmd-softworks/solara#3]
inject button pressed
injection starts
doesnt inject
i tap on solara
it stops responding
crash

this happens EVERY TIME

additional context edit:
- i use bloxstrap 2.5.4
- i DO NOT use shaders
- pre-fix for breaking games it worked
- i use the website to launch roblox... so i cant use admin

**Comment by DJ5-1** [comment]
Did you opened the launcher with the admin privileges?
Also if you have euro truck Roblox version(shader version) uninstall that shit, + of you have Bloxstrap that's higher the version of v.2.5.4 or anything like that, it will stop injecting  too

**Comment by chicken-nugget1104** [comment]
> Did you opened the launcher with the admin privileges? Also if you have euro truck Roblox version(shader version) uninstall that shit, + if you have Bloxstrap that's higher the version of v.2.5.4 or anything like that, it will stop injecting too

i dont have that shader thing, i dont use shaders.

and uh i open it from the site (because thats how i always have) so no i havent ran as admin?

also i dunno my bloxstrap ver

**Comment by chicken-nugget1104** [comment]
> > Did you opened the launcher with the admin privileges? Also if you have euro truck Roblox version(shader version) uninstall that shit, + if you have Bloxstrap that's higher the version of v.2.5.4 or anything like that, it will stop injecting too
> 
> i dont have that shader thing, i dont use shaders.
> 
> and uh i open it from the site (because thats how i always have) so no i havent ran as admin?
> 
> also i dunno my bloxstrap ver but it worked pre-fix for breaking games, ever since then it stopped working for me, which is ODD...

just downgraded bloxstrap (which hasnt been a problem before) didnt fix anything, so that isnt the problem.

**Comment by chicken-nugget1104** [comment]
@DJ5-1

**Comment by rhuda21** [comment]
did you add exclusion of these folders to antivirus?

Wherever you put the bootstrapper
%localappdata%\Temp
C:/ProgramData/Solara

**Comment by chicken-nugget1104** [comment]
> did you add exclusion of these folders to antivirus?
> 
> Wherever you put the bootstrapper %localappdata%\Temp C:/ProgramData/Solara

How would i do that because that may be it? but then again it always worked before

**Comment by rhuda21** [comment]
did you roblox channel get changed?

Check %localappdata%\Bloxstrap\Settings.json

Line 11 should say  :  "Channel": "Live",

**Comment by rhuda21** [comment]
another solution could be a full Solara reload, by deleting its directories

**Comment by rhuda21** [comment]
> * i use the website to launch roblox... so i cant use admin

when you say this do you mean you don't cant run things as admin?

**Comment by chicken-nugget1104** [comment]
> > * i use the website to launch roblox... so i cant use admin
> 
> when you say this do you mean you can't run things as admin?

i can, but since i use the website i cannot change if it will run as admin or not

**Comment by chicken-nugget1104** [comment]
> another solution could be a full Solara reload, by deleting its directories
> 
> but that would probably delete any saved scripts
> 
> C:\ProgramData\Solara %localappdata%\Temp - deleting the contents of it (make sure all apps are closed when you do this)

i guess i can try??

**Comment by chicken-nugget1104** [comment]
ok so its new behaviour is i tap inject then it instant freezes (me not having to do ANYTHING) and then crashes...

**Comment by rhuda21** [comment]
have you tried Roblox reinstallation?

**Comment by chicken-nugget1104** [comment]
> have you tried Roblox reinstallation?
> 
> Uninstalling Bloxstrap and deleting this folder? %localappdata%\Bloxstrap. This does clear Roblox app data so make sure you know the account password and stuff

... are you sure its roblox and not solara?

**Comment by chicken-nugget1104** [comment]
![image](https://github.com/user-attachments/assets/59d5bf97-9001-4e7b-bc75-7ac5dc108d89)
cant even boot now

**Comment by rhuda21** [comment]
use a vpn

**Comment by rhuda21** [comment]
https://www.microsoft.com/store/productId/9PKL3H9LWMB7?ocid=pdpshare - You can try this VPN its from Microsoft Store so you can't get virus

**Comment by chicken-nugget1104** [comment]
> https://www.microsoft.com/store/productId/9PKL3H9LWMB7?ocid=pdpshare - You can try this VPN its from Microsoft Store so you can't get virus

ok well i got a vpn (nordVPN) but im in the us and it worked befor

**Comment by rhuda21** [comment]
is your bootstrapper the latest one from discord?

also using bypasser gives old bootstrapper link

**Comment by rhuda21** [comment]
> > have you tried Roblox reinstallation?
> > Uninstalling Bloxstrap and deleting this folder? %localappdata%\Bloxstrap. This does clear Roblox app data so make sure you know the account password and stuff
> 
> ... are you sure its roblox and not solara?

Solara works fine for me so yh, i even tried launching from web (which u do) and it worked

**Comment by rhuda21** [comment]
> is your bootstrapper the latest one from discord?
> 
> also using bypasser gives old bootstrapper link

https://raw.githubusercontent.com/cmd-softworks/solara/main/Bootstrapper.exe This is the link for the bootstrapper

**Comment by chicken-nugget1104** [comment]
> > is your bootstrapper the latest one from discord?
> > also using bypasser gives old bootstrapper link
> 
> https://raw.githubusercontent.com/cmd-softworks/solara/main/Bootstrapper.exe This is the link for the bootstrapper btw

mate... i cant USE linkvertise it keeps telling me to uh turn off ad blocker or VPN, i dont use my VPN at all nor have an ad blocker, so i had to use a bypasser

**Comment by rhuda21** [comment]
> > > is your bootstrapper the latest one from discord?
> > > also using bypasser gives old bootstrapper link
> > 
> > 
> > https://raw.githubusercontent.com/cmd-softworks/solara/main/Bootstrapper.exe This is the link for the bootstrapper btw
> 
> mate... i cant USE linkvertise it keeps telling me to uh turn off ad blocker or VPN, i dont use my VPN at all nor have an ad blocker, so i had to use a bypasser

i give you direct link

**Comment by chicken-nugget1104** [comment]
same one i have, same errro

**Comment by rhuda21** [comment]
> same one i have, same error

i wonder if nord blocks it, try a different vpn i'd say

i dont use NordVPN btw

**Comment by chicken-nugget1104** [comment]
> > same one i have, same error
> 
> i wonder if nord blocks it, try a different vpn i'd say
> 
> i dont use NordVPN btw

i have no other vpn's and also my vpn is always off

**Comment by rhuda21** [comment]
> > > same one i have, same error
> > 
> > 
> > i wonder if nord blocks it, try a different vpn i'd say
> > i dont use NordVPN btw
> 
> i have no other vpn's and also my vpn is always off

wdym did you try with nord and without nord

**Comment by chicken-nugget1104** [comment]
well now the bootstrapper works, gunna try injecting

> > > > same one i have, same error
> > > 
> > > 
> > > i wonder if nord blocks it, try a different vpn i'd say
> > > i dont use NordVPN btw
> > 
> > 
> > i have no other vpn's and also my vpn is always off
> 
> wdym did you try with nord and without nord

wow now it works (apparently it wasnt off for some reason, swear it was)

**Comment by rhuda21** [comment]
> well now the bootstrapper works, gunna try injecting
> 
> > > > > same one i have, same error
> > > > 
> > > > 
> > > > i wonder if nord blocks it, try a different vpn i'd say
> > > > i dont use NordVPN btw
> > > 
> > > 
> > > i have no other vpn's and also my vpn is always off
> > 
> > 
> > wdym did you try with nord and without nord
> 
> wow now it works (apparently it wasnt off for some reason, swear it was)

i think some vpn turns themselves on for security

**Comment by rhuda21** [comment]
the quote chain goin crazy lol

**Comment by chicken-nugget1104** [comment]
lets go it works
